{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "k8s-app.name" $ }}-rolebinding-{{ .name }}
  labels:
    {{- include "k8s-app.labels" $ | nindent 4 }}
  {{- if $.Values.rbac.additionalLabels }}
    {{ toYaml $.Values.rbac.additionalLabels | indent 4 }}
  {{- end }}
  {{- if $.Values.rbac.annotations }}
  annotations:
    {{ toYaml $.Values.rbac.annotations | indent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "k8s-app.name" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.rbac.serviceAccount.name }}
    name: {{ $.Values.rbac.serviceAccount.name }}
  {{- else }}
    name: {{ template "k8s-app.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}