{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "k8s-app.name" $ }}-role-{{ .name }}
  labels:
    {{- include "k8s-app.labels" $ | nindent 4 }}
  {{- if $.Values.rbac.additionalLabels }}
    {{- toYaml $.Values.rbac.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if $.Values.rbac.annotations }}
  annotations:
    {{- toYaml $.Values.rbac.annotations | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}
{{- end }}