{{- if (.Values.secret).enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-app.name" $ }}-{{ $nameSuffix }}
  labels:
  {{- include "k8s-app.labels" $ | nindent 4 }}
{{- if $.Values.secret.additionalLabels }}
{{- toYaml $.Values.secret.additionalLabels | nindent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{- toYaml $.Values.secret.annotations | nindent 4 }}
{{- end }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- with .encodedData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}