{{- if and (.Values.serviceMonitor).enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: {{ template "k8s-app.name" . }}-svc-monitor
  labels:
  {{- include "k8s-app.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
  {{- end }}
  {{- if or .Values.serviceMonitor.annotations }}
  annotations:
    {{ toYaml .Values.serviceMonitor.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{ include "k8s-app.labels" . | indent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
    {{ toYaml .Values.serviceMonitor.endpoints | indent 4 }}
{{- end }}