{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "k8s-app.name" .) .Values.rbac.serviceAccount.name }}
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    {{- with .Values.rbac.serviceAccount.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.rbac.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}